Added watch subcommand
seaofvoices/darklua pull request #123
Opened 2023-08-30 16:06 UTC by Stefanuk12

2023-09-11 15:15 UTC, jeparlefrancais requested changes

2023-09-18 19:57 UTC, Stefanuk12 commented on src/cli/mod.rs
> +    Watch(process::Options),
Hey, sorry for the late reply. Been trying to get this to work and I'm getting the following error: ``(dyn Rule + 'static)` cannot be shared between threads safely
the trait `Sync` is not implemented for `(dyn Rule + 'static)``

I mostly copy pasted the code from the watch file.

```rs
        let mut watcher = notify::recommended_watcher(move |res: Result<notify::Event, notify::Error>| {
            match res {
                Ok(event) => {
                    if event.kind.is_create() || event.kind.is_modify() {
                        let Err(e) = process(*(resources.clone()), *(process_options.clone())) else { return };
                        log::error!("there was an process error while attempting to bundle: {:?}", e);
                    }
                }
                Err(err) => {
                    log::error!("there was an watcher error while attempting to bundle: {:?}", err);
                }
            }
        }).expect("failed to create watcher");
```

2023-09-23 20:43 UTC, jeparlefrancais commented on src/cli/mod.rs
> +    Watch(process::Options),
I sent you an invite on discord, we could work on this together if you want some help 🙂

2023-10-01 14:34 UTC, jeparlefrancais approved these changes

2023-10-05 15:18 UTC, merged